# -*- coding: utf-8 -*-
"""【公開用】05章_コピペで簡単実行！キテレツおもしろ自然言語処理_付録コード.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BiZhrQF3pJtqp0fhpqIrOfKabqoK35-X
"""



"""ここに掲載されているコードは、  
『コピペで簡単実行！キテレツおもしろ自然言語処理～PythonとColaboratoryで身につく基礎の基礎』書籍の付録です。    
本ファイルの公開用URLや、本ファイル内のコードを、みだりに他の人へ共有しないでください。  

本ファイルは、書籍に記載のコードのコピペの手間を省くために作られました。  
本ファイルの公開用URLにアクセスすると、  
お手元のGoogleアカウントに本ファイルのコピーが作成されます。  
（つまり、コレをご覧になっているということは、コピーをご覧になっています）    
そのコピーは、あなただけのファイルとして生成されるため、    
書籍をお買い求め済みの方は、自由に変更したり実行したり保存したりして問題ありません。   

初期状態では、ご参考までに筆者が実行した出力結果を残してあります。  
ご自身で実行する際には、「編集」⇒「出力を全て消去」により、  
出力結果を消去してから実行なさると良いでしょう。  

※注：Googleの公式が作成したファイルではないため、実行時に  
「警告: このノートブックは Google が作成したものではありません。」  
という警告が出ます。  
気になる方は、ご自身の環境に都度コードをコピーして実行しても良いでしょう。


"""



"""■  GoogleDriveのマウントコマンド：

"""

from google.colab import drive
drive.mount('/content/drive')

"""■ モデルファイルのダウンロード："""

# KITERETUフォルダをマウントしたGoogleDriveフォルダ(MyDrive)内に作成する
!mkdir -p /content/drive/MyDrive/KITERETU
# Word2Vecの学習済みモデルをそのフォルダにダウンロードする(3ファイルで1セット:400MB弱ほど)
!curl -o /content/drive/MyDrive/KITERETU/gw2v160.model https://storage.googleapis.com/nlp_youwht/w2v/gw2v160.model
!curl -o /content/drive/MyDrive/KITERETU/gw2v160.model.trainables.syn1neg.npy https://storage.googleapis.com/nlp_youwht/w2v/gw2v160.model.trainables.syn1neg.npy
!curl -o /content/drive/MyDrive/KITERETU/gw2v160.model.wv.vectors.npy https://storage.googleapis.com/nlp_youwht/w2v/gw2v160.model.wv.vectors.npy

"""■ モデルのロードと使い方："""

from gensim.models.word2vec import Word2Vec

# 学習済みモデルのロード
model_file_path = '/content/drive/MyDrive/KITERETU/gw2v160.model'
model = Word2Vec.load(model_file_path)

# モデル内に登録されている単語リストの長さをlen関数で見る（＝単語数）
print(len(model.wv.vocab.keys()))

# 「群馬」に似ている単語TOP7を書き出す
out = model.wv.most_similar(positive=[u'群馬'], topn=7)
print(out)

"""■ カレーに似た単語を表示する："""

out = model.wv.most_similar(positive=[u'カレー'], topn=7)
print(out)

"""■ 群馬の中身を見る："""

print(model.wv[u'群馬'])

"""■ 「宇都宮」ー「栃木」＋「群馬」を求める："""

out = model.wv.most_similar(positive=[u'宇都宮', u'群馬'], negative=[u'栃木'], topn=7)
print(out)

"""■ 「東京」ー 「日本」 ＋ 「フランス」："""

out = model.wv.most_similar(positive=[u'東京', u'フランス'], negative=[u'日本'], topn=7)
print(out)

"""■ 「税金」ー 「東京」 ＋ 「江戸」："""

out = model.wv.most_similar(positive=[u'税金', u'江戸'], negative=[u'東京'], topn=7)
print(out)

"""■ 「前橋」ー「群馬」、「宇都宮」ー「栃木」：

"""

out = model.wv.most_similar(positive=[u'前橋'], negative=[u'群馬'], topn=7)
print(out)
out = model.wv.most_similar(positive=[u'宇都宮'], negative=[u'栃木'], topn=7)
print(out)

"""■ 「カレーライス」ー「カレー」："""

out = model.wv.most_similar(positive=[u'カレーライス'], negative=[u'カレー'], topn=7)
print(out)

